name: Trigger Jenkins Job

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  trigger-job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Get the branch and build Jenkins URL
      - name: Get branch name and build Jenkins URL
        run: |
          BRANCH_NAME="main"
          JENKINS_URL="https://automation.prms.cgiar.org/job/innovation-catalog-${BRANCH_NAME}/build"
          echo "Jenkins job URL for the branch $BRANCH_NAME is: $JENKINS_URL"
          echo "JENKINS_URL=${JENKINS_URL}" >> $GITHUB_ENV

      # Step 2: Trigger Jenkins Job
      - name: Trigger Jenkins Job
        run: |
          curl -X POST ${{ env.JENKINS_URL }} \
            --user ${{ secrets.JENKINS_USERNAME }}:${{ secrets.JENKINS_API_TOKEN }}
        env:
          JENKINS_URL: ${{ env.JENKINS_URL }}
          JENKINS_USERNAME: ${{ secrets.JENKINS_USERNAME }}
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
